- name: Run docker plugin
  hosts: localhost
  tasks:
      - name: Setup
        include: 'tasks/setup.yml'
        tags:
            - setup

      - name: Create container
        include: 'tasks/create.yml'
        tags:
            - create
        when: provision.create | default(False)


      - name: List tags/images/containers
        include: 'tasks/list.yml'
        tags:
            - list
        when: (provision.list.images | default(False)) or
              (provision.list.tags | default(False))
